// Builds the EvaluationContext object from the static and
// runtime reports. This is the "scope" that rule conditions
// run inside — every field a condition can access lives here.
//
// WHY THIS FILE EXISTS:
// The reports store data in their own formats (strings for MB
// values, arrays for commits, etc). The EvaluationContext
// normalises everything into clean, easy-to-use values so
// condition expressions like "payloadMB > 3" just work without
// needing to call parseFloat() or .length inside the rule itself.
// ─────────────────────────────────────────────────────────────

import { StaticReport, RuntimeReport } from "../../shared/src/types";
import { EvaluationContext } from "./types";

/**
 * Assembles a flat EvaluationContext from the static and
 * runtime reports.
 *
 * Both parameters are optional because:
 *   - A "static-only" rule only needs the static report
 *   - A "runtime-only" rule only needs the runtime report
 *   - A "cross" rule needs both
 *
 * If a report is missing, its corresponding fields are set
 * to safe zero/empty defaults so conditions that check them
 * simply evaluate to false instead of throwing an error.
 *
 * @param staticReport  — result of the Static Analyzer (or null)
 * @param runtimeReport — result of the Runtime Profiler  (or null)
 */
export function buildContext(
  staticReport:  StaticReport  | null,
  runtimeReport: RuntimeReport | null,
): EvaluationContext {

  // ── Runtime fields ──────────────────────────────────────────
  // Pull every value we need from the runtime report.
  // Default to 0 / empty if the runtime report wasn't provided.

  const metrics = runtimeReport?.metrics ?? {
    lcp: 0, fcp: 0, cls: 0, inp: 0, ttfb: 0,
  };

  const renderTime       = runtimeReport?.renderTime       ?? 0;
  const rerenders        = runtimeReport?.rerenders        ?? {};
  const commitDurations  = runtimeReport?.commitDurations  ?? [];
  const domNodes         = runtimeReport?.stats?.domNodes  ?? 0;
  const performanceScore = runtimeReport?.performanceScore ?? 0;
  const errors           = runtimeReport?.errors           ?? [];

  // payloadMB and jsHeapMB are stored as strings ("1.49") in the
  // report for display purposes. Convert them to numbers here so
  // conditions can compare them with > < operators directly.
  const payloadMB = parseFloat(runtimeReport?.stats?.payloadMB ?? "0");
  const jsHeapMB  = parseFloat(runtimeReport?.stats?.jsHeapMB  ?? "0");

  // ── Derived runtime values ──────────────────────────────────
  // These are calculated from the raw data above for convenience.
  // Putting the math here keeps the rule condition strings clean.

  // Slowest single commit — 0 if no commits were recorded
  const slowestCommit = commitDurations.length > 0
    ? Math.max(...commitDurations)
    : 0;

  // Average commit duration — 0 if no commits were recorded
  const avgCommit = commitDurations.length > 0
    ? commitDurations.reduce((a, b) => a + b, 0) / commitDurations.length
    : 0;

  // How many commits exceeded the 16ms 60fps frame budget
  // Any commit over 16ms causes a visible dropped frame
  const slowCommitCount = commitDurations.filter(d => d > 16).length;

  // Error/warning counts — shorthand so rules don't need to
  // write errors.filter(e => e.type === 'error').length every time
  const errorCount   = errors.filter(e => e.type === "error").length;
  const warningCount = errors.filter(e => e.type === "warning").length;

  // Find the component with the most re-renders — this is the
  // primary suspect when the "excessive rerenders" rule fires.
  // Returns ["ComponentName", count] or ["", 0] if no data.
  const rerenderEntries = Object.entries(rerenders);
  const [topRerenderComponent, topRerenderCount] =
    rerenderEntries.length > 0
      ? rerenderEntries.reduce(
          (max, entry) => (entry[1] > max[1] ? entry : max),
          ["", 0] as [string, number],
        )
      : ["", 0];

  // ── Static fields ────────────────────────────────────────────
  // Pull the issues array from the static report.
  // Default to empty array if the static report wasn't provided.

  const issues = staticReport?.issues ?? [];

  const criticalIssueCount = issues.filter(i => i.severity === "critical").length;
  const warningIssueCount  = issues.filter(i => i.severity === "warning").length;

  // hasIssue(prefix) — returns true if any issue ID starts with
  // the given prefix. Used in conditions like: hasIssue('missing-memo')
  //
  // The issue IDs are generated by the detectors like this:
  //   generateIssueId('missing-memo', filePath, line)
  //   → "missing-memo-src/components/Button.tsx-42"
  //
  // So checking startsWith('missing-memo') catches all of them
  // regardless of which file or line they came from.
  const hasIssue = (prefix: string): boolean =>
    issues.some(i => i.id.startsWith(prefix));

  // getIssues(prefix) — returns all matching issue objects.
  // Used when a condition or message needs the actual issue data.
  const getIssues = (prefix: string) =>
    issues.filter(i => i.id.startsWith(prefix));

  // ── Assemble the full context ─────────────────────────────
  return {
    // Runtime
    metrics,
    renderTime,
    rerenders,
    commitDurations,
    slowestCommit,
    avgCommit,
    slowCommitCount,
    domNodes,
    payloadMB,
    jsHeapMB,
    errors,
    errorCount,
    warningCount,
    performanceScore,
    topRerenderComponent,
    topRerenderCount,

    // Static
    issues,
    criticalIssueCount,
    warningIssueCount,
    hasIssue,
    getIssues,
  };
}